version: "3.8"

services:
# Development container.
# Runs in debug mode and live-reloading on every source file update.
  e-shop-cdn:
    hostname: e-shop-cdn
    restart: unless-stopped
    build:
# if use private libs uncomment this
#      args:
#        - GITHUB_TOKEN=${GITHUB_TOKEN}
      context: ./
      dockerfile: Dockerfile
      target: dev
    # command: tail -f /dev/null # for debug only
    env_file:
      - .env.docker # separate configs
    volumes:
      - ./:/srv # for dev target only
      # - .env:/srv/.env # for production target only
    ports:
      - 8888:${APP_PORT}